# Generated by Django 5.2.15 on 2026-07-01 07:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(blank=True, default='unknown@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LossRecord',
            fields=[
                ('loss_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_lost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loss_date', models.DateField()),
                ('reason', models.TextField()),
                ('loss_location', models.CharField(default='Main Warehouse', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('procurement_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('delivery_location', models.CharField(default='Main Warehouse', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(max_length=255)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('payment_terms', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_category', models.CharField(blank=True, choices=[('Raw Material', 'Raw Material Purchase'), ('Salaries', 'Employee Salaries'), ('Services', 'External services'), ('Overhead', 'Overhead costs')], max_length=25, null=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('invoice_type', models.CharField(choices=[('CUSTOMER', 'Customer invoice(Receivable)'), ('SUPPLIER', 'Supplier invoice(Payable)')], default='CUSTOMER', max_length=255)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.dispatchrecord')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('finance_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='EXPENSE', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField()),
                ('category', models.CharField(choices=[('Sales', 'Sales'), ('Labor', 'Labor'), ('Overhead', 'Overhead'), ('Procurement', 'Procurement'), ('Customer refund', 'Customer refund'), ('Loss', 'Loss')], default='SALES', max_length=20)),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.invoice')),
                ('loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.lossrecord')),
                ('procurement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.procurementorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('production_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any issues or notes during this production run.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.employee')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.rawmaterial')),
            ],
            options={
                'ordering': ['-actual_start_date'],
            },
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productionorder'),
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_order', to='core.rawmaterial'),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_returned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_for_return', models.TextField(default='No reason provided', max_length=255)),
                ('quality_control_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Rejected', max_length=255)),
                ('return_warehouse_location', models.CharField(default='Main Warehouse', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispatchrecord')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_order', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('invoice_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the goods or manufacturing service rendered.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage applied to this line (e.g., 16.00 for 16%).', max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line', to='core.employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('Production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line', to='core.productionorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line', to='core.supplier')),
            ],
            options={
                'ordering': ['invoice_line_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_start_date', models.DateField()),
                ('production_end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_order', to='core.employee')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='core.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='productionorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderInstruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('machine', models.CharField(blank=True, default='No machine assigned', max_length=255, null=True)),
                ('instruction_text', models.TextField()),
                ('estimated_time_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rawmaterial')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.workorder')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_record', to='core.rawmaterial')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'unique_together': {('material', 'location')},
            },
        ),
    ]
