# Generated by Django 5.2.15 on 2026-07-16 09:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='name is auto-generated after the selected product if left blank.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this is the active recipe used for live manufacturing runs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bills of Materials',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('shipping_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(blank=True, default='unknown@example.com', max_length=254)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly rate must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='LossRecord',
            fields=[
                ('loss_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_lost', models.DecimalField(decimal_places=2, help_text='Quantity lost must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('loss_date', models.DateField()),
                ('reason', models.TextField()),
                ('loss_location', models.CharField(default='Main Warehouse', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('procurement_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity ordered must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per unit must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total cost is automatically calculated based on quantity ordered and price per unit.', max_digits=10)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=255)),
                ('delivery_location', models.CharField(default='Main Warehouse', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Good'), ('INTERMEDIATE', 'component / sub-assembly')], default='FINISHED', max_length=20)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit, auto-generated if left blank.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(max_length=255)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Ordered quantity cannot be negative.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(editable=False, help_text='System generated unique purchase order number.', max_length=100, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Supplier'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Fully Received / Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Delivery instructions or terms')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, help_text='Unique identifier for the invoice. Auto-generated if left blank.', max_length=255, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial Payment'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.dispatchrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('finance_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=10)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('LABOR', 'Labor cost'), ('OVERHEAD', 'Overhead'), ('PROCUREMENT', 'material Procurement'), ('CUSTOMER_REFUND', 'Customer refund'), ('LOSS', 'Inventory Loss')], default='SALES', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('entry_date', models.DateField()),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.invoice')),
                ('loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.lossrecord')),
                ('procurement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.procurementorder')),
            ],
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='product',
            field=models.ForeignKey(help_text='Only raw materials can be selected for procurement.', limit_choices_to={'product_type': 'RAW'}, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_order', to='core.product'),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='product',
            field=models.ForeignKey(help_text='Only finished goods can be selected for dispatch.', limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='core.product'),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('bom_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='The precise amount needed to create 1 unit of the parent product.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.billofmaterial')),
                ('component', models.ForeignKey(help_text='A raw material, retail item or intermediate sub-assembly required for production.', limit_choices_to={'product_type__in': ['RAW', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(help_text='The finished or intermediate good this recipe creates.', limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.product'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique identifier for the purchase invoice from the supplier.', max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid')], default='UNPAID', max_length=20)),
                ('paid_date', models.DateField(blank=True, help_text='Date when this invoice was fully settled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procurement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='core.procurementorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='core.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='The source Purchase Order this delivery belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='core.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Negotiated cost per unit for this order.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('product', models.ForeignKey(help_text='Only raw materials can be ordered via purchase orders.', limit_choices_to={'product_type': 'RAW'}, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='core.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card Transfer'), ('TRANSFER', 'Bank Transfer')], max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference/receipt ID for Bank and Mobile money transfers', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='core.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_returned', models.DecimalField(decimal_places=2, help_text='Quantity returned must be a positive amount greater than zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason_for_return', models.TextField(default='No reason provided', max_length=255)),
                ('quality_control_status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255)),
                ('return_warehouse_location', models.CharField(default='Main Warehouse', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispatchrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoicePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card Transfer'), ('TRANSFER', 'Bank Transfer')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payments', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved (Pending Fulfillment)'), ('partially_dispatched', 'Partially Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='core.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_dispatched', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Use positive numbers for stock additions, negative numbers for deductions.', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Goods Receipt (Supplier Purchase)'), ('PRODUCTION_OUTPUT', 'Production Output (Finished Goods)'), ('PRODUCTION_CONSUMPTION', 'Material Consumption (BOM Use)'), ('SHIPMENT', 'Customer Shipment (Sales Order)'), ('ADJUSTMENT', 'Manual Stock Adjustment / Correction')], max_length=30)),
                ('reference_type', models.CharField(blank=True, help_text="The document type (e.g., 'PO', 'PRODUCTION_ORDER', 'INVOICE')", max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='The exact ID of the source document.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for adjustment, operator name, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='procurementorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_order', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('production_start_date', models.DateField()),
                ('production_end_date', models.DateField(blank=True, null=True)),
                ('bill_of_material', models.ForeignKey(blank=True, help_text='The snapshot version of the recipe locked in for this specific operational run.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.billofmaterial')),
                ('employee', models.ManyToManyField(help_text='Employees assigned to this work order.', related_name='assigned_work_order', to='core.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('production_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity to be produced in this specific run.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any issues or notes during this production run.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ManyToManyField(blank=True, help_text='Employees assigned to this production run.', related_name='production_runs', to='core.employee')),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity available cannot drop below zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('location', models.CharField(default='Main Warehouse', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderInstruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(blank=True, null=True)),
                ('step_name', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.CharField(blank=True, default='No machine assigned', max_length=255, null=True)),
                ('instruction_text', models.TextField()),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.workorder')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('work_order', 'step_number')},
            },
        ),
    ]
