# Generated by Django 5.2.15 on 2026-07-16 13:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='is_stock_deducted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='core.product'),
        ),
    ]
