# Generated by Django 5.2.15 on 2026-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=255, null=True),
        ),
    ]
