# Generated by Django 5.2.15 on 2026-07-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='quantity_consumed',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='quantity_consumed',
        ),
    ]
