# Generated by Django 5.2.15 on 2026-07-17 12:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dispatchrecord_is_stock_deducted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='quantity',
            new_name='quantity_produced',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ordered_quantity',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='reference_type',
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Preparing'), ('shipped', 'Shipped / In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='dispatch_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='core.dispatchrecord'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='core.workorder'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='delivery_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Theoretical quantity calculated from BOM.', max_digits=10)),
                ('quantity_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The actual physical quantity consumed during this run.', max_digits=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usages', to='core.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='core.workorder')),
            ],
        ),
    ]
