# Generated by Django 5.2.15 on 2026-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoice_expense_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementorder',
            old_name='quantity_ordered',
            new_name='quantity',
        ),
    ]
