# Generated by Django 5.2.15 on 2026-07-08 11:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_quantity_ordered_procurementorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_level',
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ordered quantity cannot be negative.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
