# Generated by Django 5.2.15 on 2026-07-20 14:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_quantity_workorder_quantity_produced_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchrecord',
            old_name='sales_order',
            new_name='sales_order_item',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='production_end_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Moving weighted average cost calculated from delivered procurements.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_inventory_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', editable=False, help_text='Automatically managed based on step completion statuses.', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
