# Generated by Django 5.2.15 on 2026-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_productionorder_quantity_consumed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='employee',
        ),
        migrations.AddField(
            model_name='workorder',
            name='employee',
            field=models.ManyToManyField(help_text='Employees assigned to this work order.', related_name='assigned_work_order', to='core.employee'),
        ),
    ]
