# Generated by Django 5.2.15 on 2026-07-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_sales_order_dispatchrecord_sales_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementorder',
            name='supplier',
        ),
    ]
