# Generated by Django 5.2.15 on 2026-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_workorder_employee_workorder_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='employee',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='employee',
            field=models.ManyToManyField(blank=True, help_text='Employees assigned to this production run.', related_name='production_runs', to='core.employee'),
        ),
    ]
