# Generated by Django 5.2.15 on 2026-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_workorder_production_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderinstruction',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='workorderinstruction',
            name='step_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workorderinstruction',
            name='step_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
