# Generated by Django 5.2.15 on 2026-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_procurementorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Automatically captures when status changes to Delivered.', null=True),
        ),
    ]
