# Generated by Django 5.2.15 on 2026-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productionorder_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='employee',
            field=models.ManyToManyField(help_text='Employees assigned to this production run.', related_name='production_runs', to='core.employee'),
        ),
    ]
