# Generated by Django 5.2.15 on 2026-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workorderinstruction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='IN_PROGRESS', max_length=20),
        ),
    ]
