# Generated by Django 5.2.15 on 2026-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_procurementorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='production_end_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Automatically captured when work order status turns to Completed.', null=True),
        ),
    ]
