# Generated by Django 5.2.15 on 2026-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productionorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='actual_start_date',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='quantity_produced',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='employee',
            field=models.ManyToManyField(blank=True, help_text='Employees assigned to this production run.', related_name='production_runs', to='core.employee'),
        ),
    ]
