# Generated by Django 5.2.15 on 2026-07-21 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workorder_production_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.billofmaterial'),
        ),
        migrations.AlterField(
            model_name='workordermaterialline',
            name='raw_material',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['RAW']}, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usages', to='core.product'),
        ),
    ]
