# Generated by Django 5.2.15 on 2026-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bomitem_bom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workordermaterialline',
            old_name='raw_material',
            new_name='component',
        ),
    ]
