# Generated by Django 5.2.15 on 2026-07-10 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productionorder_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='quantity_produced',
            new_name='quantity',
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this is the active recipe used for live manufacturing runs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The finished or intermediate good this recipe creates.', limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.product')),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bills of Materials',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='bill_of_material',
            field=models.ForeignKey(blank=True, help_text='The snapshot version of the recipe locked in for this specific operational run.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.billofmaterial'),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('bom_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='The precise amount needed to create 1 unit of the parent product.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.billofmaterial')),
                ('component', models.ForeignKey(help_text='A raw material, retail item or intermediate sub-assembly required for production.', limit_choices_to={'product_type__in': ['RAW', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='core.product')),
            ],
        ),
    ]
