# Generated by Django 5.2.15 on 2026-07-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_raw_material_workordermaterialline_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workordermaterialline',
            options={'verbose_name': 'Work Order Material Line', 'verbose_name_plural': 'Work Order Material Lines'},
        ),
        migrations.AlterField(
            model_name='workordermaterialline',
            name='component',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['RAW', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usages', to='core.product'),
        ),
        migrations.AlterUniqueTogether(
            name='workordermaterialline',
            unique_together={('work_order', 'component')},
        ),
    ]
