# Generated by Django 5.2.15 on 2026-07-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workordermaterialline_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='unit_price',
        ),
    ]
