# Generated by Django 5.2.15 on 2026-07-23 11:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_salesorderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for Finished Goods. Leave blank for raw materials and intermediates.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Manufacturing cost per unit for this specific batch.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
