# Generated by Django 5.2.15 on 2026-07-14 07:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_purchaseinvoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorder',
            old_name='updated_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity to be produced in this specific run.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction reference/receipt ID for Bank and Mobile money transfers', max_length=100, null=True),
        ),
    ]
