# Generated by Django 5.2.15 on 2026-07-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_updated_at_productionorder_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Good'), ('INTERMEDIATE', 'component / sub-assembly')], default='FINISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.product'),
        ),
    ]
