# Generated by Django 5.2.15 on 2026-07-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_sku_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.product'),
        ),
    ]
