# Generated by Django 5.2.15 on 2026-07-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='name',
            field=models.CharField(blank=True, help_text='name is auto-generated after the selected product if left blank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesinvoicepayments',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payments', to='core.invoice'),
        ),
    ]
