# Generated by Django 5.2.15 on 2026-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_invoice_paid_date_alter_billofmaterial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial Payment'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=255),
        ),
    ]
