# Generated by Django 5.2.15 on 2026-07-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_productionorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_order_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit, auto-generated if left blank.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Supplier'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Fully Received / Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'FINISHED'}, on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='core.product'),
        ),
    ]
