# Generated by Django 5.2.15 on 2026-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card Transfer'), ('TRANSFER', 'Bank Transfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salesinvoicepayments',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card Transfer'), ('TRANSFER', 'Bank Transfer')], max_length=50),
        ),
    ]
