# Generated by Django 5.2.15 on 2026-07-31 10:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workorder_work_order_code_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_allocated',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Stock reserved for active Work Orders currently IN_PROGRESS.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_inventory_allocated',
            field=models.BooleanField(default=False, help_text='Flag indicating BOM expected stock has been reserved on IN_PROGRESS.'),
        ),
        migrations.AddField(
            model_name='workordermaterialline',
            name='quantity_issued',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Automated counter tracking stock already deducted for this line in prior saves.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unreserved stock physically available for new production orders. Cannot drop below zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.product'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='core.product'),
        ),
    ]
