# Generated by Django 5.2.15 on 2026-08-03 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_inventory_quantity_allocated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrecord',
            name='sales_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_records', to='core.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ON_HOLD_SHORTAGE', 'On Hold (Stock Shortage)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
    ]
