# Generated by Django 5.2.8 on 2026-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dispatchrecord_sales_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='production_order_code',
            field=models.CharField(blank=True, editable=False, help_text='System-generated unique production order code.', max_length=20, null=True, unique=True),
        ),
    ]
