# Generated by Django 5.2.8 on 2026-08-04 08:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productionorder_production_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossrecord',
            name='loss_date',
        ),
        migrations.RemoveField(
            model_name='lossrecord',
            name='loss_location',
        ),
        migrations.RemoveField(
            model_name='lossrecord',
            name='reason',
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='efficiency_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Material utilization efficiency rate percentage.', max_digits=10),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='financial_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Financial cost impact (quantity_lost * unit_cost).', max_digits=10),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='loss_type',
            field=models.CharField(choices=[('OVER_CONSUMPTION', 'Material Over-consumption / Scrap'), ('EFFICIENT_SAVINGS', 'Material Savings / Efficiency'), ('EXACT', 'Exact Match / Zero Variance'), ('DAMAGE', 'Physical Damage / Spoilage'), ('EXPIRATION', 'Expired Stock')], default='EXACT', max_length=50),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Audit notes or breakdown for this variance record.'),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='quantity_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual physical quantity consumed during production.', max_digits=10),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='quantity_expected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Planned / theoretical BOM quantity required.', max_digits=10),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost of component at time of variance calculation.', max_digits=10),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='variance_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage usage variance relative to expected.', max_digits=10),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Parent Work Order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_records', to='core.workorder'),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='work_order_material_line',
            field=models.OneToOneField(blank=True, help_text='The work order material line this usage variance originates from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_record', to='core.workordermaterialline'),
        ),
        migrations.AlterField(
            model_name='lossrecord',
            name='product',
            field=models.ForeignKey(help_text='Component product associated with this loss/variance record.', on_delete=django.db.models.deletion.PROTECT, related_name='loss_records', to='core.product'),
        ),
        migrations.AlterField(
            model_name='lossrecord',
            name='quantity_lost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity variance (quantity_actual - quantity_expected).', max_digits=10),
        ),
    ]
