# Generated by Django 5.2.8 on 2026-08-04 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_lossrecord_loss_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossrecord',
            name='loss_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='loss_location',
            field=models.CharField(default='Main Warehouse', max_length=255),
        ),
        migrations.AddField(
            model_name='lossrecord',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason or notes for loss/variance.'),
        ),
    ]
