# Generated by Django 5.2.8 on 2026-08-04 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lossrecord_loss_date_lossrecord_loss_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity_dispatched',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
