# Generated by Django 5.2.8 on 2026-08-04 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_salesorderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='dispatch_code',
            field=models.CharField(blank=True, editable=False, help_text='System-generated unique dispatch code (e.g. DISP-0001).', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='dispatch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
