# Generated by Django 5.2.8 on 2026-08-04 09:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dispatchrecord_dispatch_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='SalesInvoice',
        ),
        migrations.RenameField(
            model_name='financeentry',
            old_name='Invoice',
            new_name='sales_invoice',
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='core.dispatchrecord'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the invoice. Auto-generated.', max_length=255, unique=True),
        ),
    ]
