# Generated by Django 5.2.8 on 2026-08-04 10:02

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_financeentry_invoice_salesinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the purchase invoice. Auto-generated if left blank.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_date',
            field=models.DateField(blank=True, editable=False, help_text='Date when this invoice was fully settled.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
