# Generated by Django 5.2.8 on 2026-08-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_purchaseinvoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique identifier for the purchase invoice from the supplier.', max_length=50, null=True, unique=True),
        ),
    ]
