# Generated by Django 5.2.8 on 2026-08-05 08:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_purchaseinvoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeentry',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='id',
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(help_text='Finished or Intermediate product this build recipe belongs to.', limit_choices_to={'product_type__in': ['FINISHED', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.product'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MaterialVarianceRecord',
            fields=[
                ('variance_id', models.AutoField(primary_key=True, serialize=False)),
                ('variance_code', models.CharField(blank=True, editable=False, help_text='System-generated unique material variance code.', max_length=20, null=True, unique=True)),
                ('quantity_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Planned / allocated BOM quantity required for this production run.', max_digits=10)),
                ('quantity_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual physical quantity consumed during production.', max_digits=10)),
                ('quantity_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity variance (quantity_actual - quantity_expected).', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost of component at time of variance calculation.', max_digits=10)),
                ('financial_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated financial impact (quantity_variance * unit_cost).', max_digits=10)),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage usage variance relative to expected.', max_digits=10)),
                ('efficiency_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Material utilization efficiency rate percentage.', max_digits=10)),
                ('variance_classification', models.CharField(choices=[('FAVOURABLE', 'Favourable (Material Efficiency / Saved)'), ('UNFAVOURABLE', 'Unfavourable (Waste / Over-consumption / Scrap)'), ('EXACT', 'Exact Match / Zero Variance')], default='EXACT', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Audit notes or breakdown for this variance record.')),
                ('product', models.ForeignKey(help_text='Component product associated with this variance record.', on_delete=django.db.models.deletion.PROTECT, related_name='variance_records', to='core.product')),
                ('work_order', models.ForeignKey(blank=True, help_text='Parent Work Order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variance_records', to='core.workorder')),
                ('work_order_material_line', models.OneToOneField(blank=True, help_text='The work order material line this material variance originates from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variance_record', to='core.workordermaterialline')),
            ],
        ),
        migrations.AddField(
            model_name='financeentry',
            name='material_variance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='core.materialvariancerecord'),
        ),
        migrations.DeleteModel(
            name='LossRecord',
        ),
    ]
