# Generated by Django 5.2.8 on 2026-08-05 12:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_financeentry_loss_remove_purchasepayment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermaterialline',
            name='quantity_expected',
        ),
        migrations.RemoveField(
            model_name='workordermaterialline',
            name='quantity_issued',
        ),
        migrations.AddField(
            model_name='workordermaterialline',
            name='deducted_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Tracks quantity already deducted from inventory.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workordermaterialline',
            name='quantity_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The actual physical quantity consumed during this run.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
