# Generated by Django 5.2.8 on 2026-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_workordermaterialline_quantity_expected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved (Pending Fulfillment)'), ('partially_dispatched', 'Partially Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', editable=False, help_text='Automated state machine based on items and dispatch progress.', max_length=25),
        ),
    ]
