# Generated by Django 5.2.8 on 2026-08-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer receiving this dispatch (must match Sales Order customer).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_records', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='sales_order_item',
            field=models.ForeignKey(help_text='Only active, non-completed sales order items can be selected for dispatch.', limit_choices_to={'sales_order__status__in': ['draft', 'approved', 'partially_dispatched']}, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_records', to='core.salesorderitem'),
        ),
    ]
