# Generated by Django 5.2.8 on 2026-08-11 08:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_dispatchrecord_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='parent_work_order',
            field=models.ForeignKey(blank=True, help_text='The Stage 1 Bulk Intermediate work order required prior to running packaging operations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_packaging_orders', to='core.workorder'),
        ),
        migrations.AddField(
            model_name='workordermaterialline',
            name='quantity_expected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Planned / expected component requirement for this line.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
