# Generated by Django 5.2.8 on 2026-08-11 10:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_workorder_parent_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrecord',
            name='dispatch_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Preparing'), ('shipped', 'Shipped / In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='category',
            field=models.CharField(choices=[('SALES', 'Sales'), ('LABOR', 'Labor cost'), ('OVERHEAD', 'Overhead'), ('PROCUREMENT', 'material Procurement'), ('CUSTOMER_REFUND', 'Customer refund'), ('LOSS', 'Inventory Loss')], db_index=True, default='SALES', max_length=20),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_type',
            field=models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], db_index=True, default='EXPENSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_available',
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Unreserved stock physically available for new production orders. Cannot drop below zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='materialvariancerecord',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='materialvariancerecord',
            name='variance_classification',
            field=models.CharField(choices=[('FAVOURABLE', 'Favourable (Material Efficiency / Saved)'), ('UNFAVOURABLE', 'Unfavourable (Waste / Over-consumption / Scrap)'), ('EXACT', 'Exact Match / Zero Variance')], db_index=True, default='EXACT', max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='order_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ON_HOLD_SHORTAGE', 'On Hold (Stock Shortage)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Supplier'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Fully Received / Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial Payment'), ('Unpaid', 'Unpaid')], db_index=True, default='Unpaid', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved (Pending Fulfillment)'), ('partially_dispatched', 'Partially Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', editable=False, help_text='Automated state machine based on items and dispatch progress.', max_length=25),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='production_start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', editable=False, help_text='Automatically managed based on step completion statuses.', max_length=20),
        ),
    ]
