# Generated by Django 5.2.8 on 2026-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_dispatchrecord_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='category',
            field=models.CharField(blank=True, choices=[('PRODUCTION', 'Production (Bulk Mixing)'), ('PACKAGING', 'Packaging')], help_text='Auto-assigned based on product type: INTERMEDIATE -> PRODUCTION, FINISHED -> PACKAGING.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for Finished Goods. Allowed for Sub-assemblies/Intermediates. Leave blank for raw materials.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('AWAITING_RESOLUTION', 'Awaiting Shortage Resolution'), ('ON_HOLD_SHORTAGE', 'On Hold (Bulk Shortage)')], db_index=True, default='IN_PROGRESS', help_text='State machine status of the work order run.', max_length=30),
        ),
    ]
