# Generated by Django 5.2.8 on 2026-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_workorder_category_alter_product_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='production_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('AWAITING_RESOLUTION', 'Awaiting Shortage Resolution'), ('ON_HOLD_SHORTAGE', 'On Hold (Bulk Shortage)')], db_index=True, default='DRAFT', help_text='State machine status of the work order run.', max_length=30),
        ),
    ]
