# Generated by Django 5.2.8 on 2026-08-17 07:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_workorder_production_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='actual_quantity_produced',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual physical quantity produced by operator (saved to inventory upon work order completion).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
