# Generated by Django 5.2.8 on 2026-08-17 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_workorder_actual_quantity_produced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Linked Work Order blueprint for this production run. Optional — link a Work Order to sync recipe and material allocations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='core.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actual_quantity_produced',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual physical quantity produced in this Run (saved to inventory upon work order completion).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
