# Generated by Django 5.2.8 on 2026-08-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_productionorder_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the production run was marked COMPLETED.', null=True),
        ),
    ]
