# Generated by Django 5.2.8 on 2026-08-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_productionorder_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'permissions': [('can_confirm_sales_order', 'Can confirm sales orders and generate invoices')]},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'permissions': [('can_start_production', 'Can start production on work orders'), ('can_resolve_shortage', 'Can resolve shortage on work orders')]},
        ),
    ]
