# Generated by Django 5.2.15 on 2026-08-20 13:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seed_roles_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='scrap_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scrap_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
