# Generated by Antigravity on 2026-08-21
import django.core.validators
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_sales_order_item_unit_prices(apps, schema_editor):
    SalesOrderItem = apps.get_model('core', 'SalesOrderItem')
    for item in SalesOrderItem.objects.all():
        if (item.unit_price is None or item.unit_price == Decimal('0.00')) and item.product and getattr(item.product, 'selling_price', None) is not None:
            item.unit_price = item.product.selling_price
            item.save(update_fields=['unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_workorder_scrap_quantity_scrap_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text="Unique key for the document type (e.g. 'SALES_INVOICE', 'CREDIT_NOTE', 'SALES_ORDER').", max_length=32, unique=True)),
                ('prefix', models.CharField(help_text="Prefix used in generated codes (e.g. 'SINV', 'CN', 'SO').", max_length=16)),
                ('last_sequence', models.PositiveIntegerField(default=0, help_text='Monotonically increasing sequence counter.')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoicing_policy',
            field=models.CharField(
                choices=[
                    ('ORDER_BASED', 'Invoice on Order Confirmation (Advance/Upfront)'),
                    ('DELIVERY_BASED', 'Invoice on Goods Dispatch (Post-Shipment)'),
                ],
                default='ORDER_BASED',
                help_text='Controls whether invoices are generated upon order confirmation or upon physical dispatch.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Frozen transaction unit price at order creation. Does not mutate with catalog price updates.',
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
            ),
        ),
        migrations.RunPython(backfill_sales_order_item_unit_prices, migrations.RunPython.noop),
        migrations.AddField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date.', null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_order',
            field=models.ForeignKey(
                blank=True,
                help_text='Originating sales order.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoices',
                to='core.salesorder',
            ),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Net invoice amount before taxes.',
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Total tax assessed on this invoice.',
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('POSTED', 'Posted/Issued'),
                    ('PARTIALLY_PAID', 'Partially Paid'),
                    ('PAID', 'Paid'),
                    ('CREDITED', 'Credited'),
                    ('CANCELLED', 'Cancelled'),
                ],
                db_index=True,
                default='DRAFT',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                editable=False,
                help_text='Grand total (Subtotal + Tax).',
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (e.g. 16.00 for 16% VAT).', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.salesorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('credit_note_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REFUNDED', 'Refunded')], db_index=True, default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage.', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
