# Generated by Django 5.2.15 on 2026-08-25 09:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_sales_billing_immutability_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='core.salesinvoice'),
        ),
    ]
