# Generated by Django 5.2.15 on 2026-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_creditnote_applied_amount_alter_creditnote_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='is_mrp_resolved',
            field=models.BooleanField(default=False, help_text='Indicates whether the MRP shortage evaluation for this production run has been locked/resolved.'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='resolution_applied',
            field=models.CharField(blank=True, help_text='Pathway or strategy applied to resolve MRP shortages.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the MRP shortage resolution was locked.', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('AWAITING_RESOLUTION', 'Awaiting Shortage Resolution'), ('ON_HOLD_SHORTAGE', 'On Hold (Bulk Shortage)')], db_index=True, default='DRAFT', help_text='State machine status of the work order run.', max_length=30),
        ),
    ]
