# Generated by Django 5.2.15 on 2026-08-25 12:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_productionorder_is_mrp_resolved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ON_HOLD_SHORTAGE', 'On Hold (Stock Shortage)'), ('PARTIALLY_RESOLVED', 'Partially Resolved'), ('MRP_RESOLVED', 'MRP Resolved / Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shortage_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('resolution_status', models.CharField(choices=[('NO_SHORTAGE', 'No Shortage / In Stock'), ('UNRESOLVED', 'Unresolved Shortage'), ('PO_DRAFTED', 'PO Drafted'), ('OVERRIDDEN', 'Overridden / Authorized'), ('DOWNSCALED', 'Downscaled Batch Target'), ('RESOLVED', 'Resolved')], db_index=True, default='UNRESOLVED', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_resolved_items', to='core.purchaseorder')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.productionorder')),
                ('raw_material', models.ForeignKey(limit_choices_to={'product_type__in': ['RAW', 'INTERMEDIATE']}, on_delete=django.db.models.deletion.PROTECT, related_name='production_order_items', to='core.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_resolved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Order Item',
                'verbose_name_plural': 'Production Order Items',
                'unique_together': {('production_order', 'raw_material')},
            },
        ),
    ]
