# Generated by Django 5.2.15 on 2026-08-26 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_productionorder_status_productionorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='description',
            field=models.TextField(blank=True, help_text='Audit notes or transaction description.', null=True),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='entry_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique sequential financial voucher number (e.g. FE-YYYYMM-XXXX).', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='reference_document',
            field=models.CharField(blank=True, help_text='Reference document code (e.g. SINV-..., PO-...).', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of ledger entry.'),
        ),
    ]
