# Generated by Django 5.2.15 on 2026-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_backfill_finance_entry_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.CharField(blank=True, choices=[('PRODUCTION', 'Production (Bulk Mixing)'), ('PACKAGING', 'Packaging')], editable=False, help_text='Auto-assigned based on product type: INTERMEDIATE -> PRODUCTION, FINISHED -> PACKAGING.', max_length=20, null=True),
        ),
    ]
