# Generated by Django 5.2.15 on 2026-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_supplier_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ON_HOLD_SHORTAGE', 'On Hold (Stock Shortage)'), ('PARTIALLY_RESOLVED', 'Partially Resolved'), ('AWAITING_PROCUREMENT', 'Awaiting Procurement (POs Drafted)'), ('READY_TO_START', 'Ready to Start (Stock Verified)'), ('MRP_RESOLVED', 'MRP Resolved / Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=30),
        ),
    ]
