# Generated by Django 5.2.15 on 2026-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_productionorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderitem',
            name='resolution_status',
            field=models.CharField(choices=[('NO_SHORTAGE', 'No Shortage / In Stock'), ('UNRESOLVED', 'Unresolved Shortage'), ('PO_DRAFTED', 'PO Drafted'), ('OVERRIDDEN', 'Overridden / Authorized'), ('DOWNSCALED', 'Downscaled Batch Target'), ('RESOLVED', 'Resolved'), ('CHILD_WO_CREATED', 'Sub-Assembly Work Order Spawned'), ('HOLD_ACTIVE_RUN', 'Held for Active Floor Run')], db_index=True, default='UNRESOLVED', max_length=30),
        ),
    ]
