# Generated by Django 5.2.15 on 2026-08-28 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_productionorderitem_resolution_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessExecutionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_type', models.CharField(choices=[('MRP_EVALUATION', 'MRP Shortage Evaluation'), ('PO_DRAFT', 'Auto-Draft Purchase Order'), ('BATCH_DOWNSCALE', 'Batch Downscale Target'), ('AUTO_RESUME', 'Auto-Resume On-Hold Order'), ('RECONCILIATION', 'Stock & Consumption Reconciliation'), ('ORDER_SYNC', 'Database & Order Synchronization'), ('AVCO_RECALCULATION', 'AVCO Recalculation')], db_index=True, max_length=40)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=10)),
                ('message', models.TextField(help_text='Human-readable operational execution summary.')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured operational metadata, component IDs, and delta metrics.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logged_by', models.ForeignKey(blank=True, help_text='User/Supervisor attributing this operational execution event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, help_text='Associated Production Order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='core.productionorder')),
                ('work_order', models.ForeignKey(blank=True, help_text='Associated Work Order blueprint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='core.workorder')),
            ],
            options={
                'verbose_name': 'Process Execution Log',
                'verbose_name_plural': 'Process Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
