# Generated by Django 5.2.15 on 2026-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_processexecutionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processexecutionlog',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=10),
        ),
    ]
