"""
Django settings for djangosystem project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy, reverse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8^rjb$xs$%ym9)rc2nv6boh3n7(e=m98#a9v&x^lc!+9e%is^a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ApiExceptionMiddleware',
]

ROOT_URLCONF = 'djangosystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangosystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
 
# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# Django Unfold Enterprise Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Manufacturing Command Center",
    "SITE_HEADER": "Manufacturing Command Center",
    "SITE_SUBHEADER": "Operations & Commercial Billing",
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Manufacturing & Shop-Floor",
                "icon": "precision_manufacturing",
                "items": [
                    {
                        "title": "Work Orders",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:core_workorder_changelist"),
                    },
                    {
                        "title": "Production Orders",
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:core_productionorder_changelist"),
                    },
                    {
                        "title": "Bills of Material (BOM)",
                        "icon": "schema",
                        "link": reverse_lazy("admin:core_billofmaterial_changelist"),
                    },
                ],
            },
            {
                "title": "Warehouse & Inventory",
                "icon": "warehouse",
                "items": [
                    {
                        "title": "All Warehouse Stock",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:core_inventory_changelist"),
                    },
                    {
                        "title": "Raw Material Stock",
                        "icon": "science",
                        "link": lambda request: f"{reverse('admin:core_inventory_changelist')}?product_type=RAW_CHEMICALS",
                    },
                    {
                        "title": "Packaging Stock",
                        "icon": "inventory",
                        "link": lambda request: f"{reverse('admin:core_inventory_changelist')}?product_type=PACKAGING",
                    },
                    {
                        "title": "Intermediates Stock",
                        "icon": "hourglass_top",
                        "link": lambda request: f"{reverse('admin:core_inventory_changelist')}?product_type=INTERMEDIATE",
                    },
                    {
                        "title": "Finished Goods Stock",
                        "icon": "verified",
                        "link": lambda request: f"{reverse('admin:core_inventory_changelist')}?product_type=FINISHED",
                    },
                    {
                        "title": "Products Catalog",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_product_changelist"),
                    },
                    {
                        "title": "Stock Transactions",
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:core_stocktransaction_changelist"),
                    },
                    {
                        "title": "Dispatch Records",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:core_dispatchrecord_changelist"),
                    },
                    {
                        "title": "RMA Returns",
                        "icon": "assignment_return",
                        "link": reverse_lazy("admin:core_return_changelist"),
                    },
                ],
            },
            {
                "title": "Sales & Commercial Billing",
                "icon": "receipt_long",
                "items": [
                    {
                        "title": "Sales Orders",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:core_salesorder_changelist"),
                    },
                    {
                        "title": "Sales Invoices",
                        "icon": "receipt",
                        "link": reverse_lazy("admin:core_salesinvoice_changelist"),
                    },
                    {
                        "title": "Credit Notes",
                        "icon": "credit_card",
                        "link": reverse_lazy("admin:core_creditnote_changelist"),
                    },
                    {
                        "title": "Customers",
                        "icon": "business",
                        "link": reverse_lazy("admin:core_customer_changelist"),
                    },
                    {
                        "title": "Document Sequences",
                        "icon": "pin",
                        "link": reverse_lazy("admin:core_documentsequence_changelist"),
                    },
                ],
            },
            {
                "title": "Procurement & Vendors",
                "icon": "local_shipping",
                "items": [
                    {
                        "title": "Purchase Orders",
                        "icon": "shopping_bag",
                        "link": reverse_lazy("admin:core_purchaseorder_changelist"),
                    },
                    {
                        "title": "Procurement Runs",
                        "icon": "outbox",
                        "link": reverse_lazy("admin:core_procurementorder_changelist"),
                    },
                    {
                        "title": "Purchase Invoices",
                        "icon": "payments",
                        "link": reverse_lazy("admin:core_purchaseinvoice_changelist"),
                    },
                    {
                        "title": "Suppliers",
                        "icon": "store",
                        "link": reverse_lazy("admin:core_supplier_changelist"),
                    },
                ],
            },
            {
                "title": "HR & Identity Access",
                "icon": "groups",
                "items": [
                    {
                        "title": "Employees",
                        "icon": "badge",
                        "link": reverse_lazy("admin:core_employee_changelist"),
                    },
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Roles & Groups",
                        "icon": "security",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": "Finance & Analytics",
                "icon": "account_balance",
                "items": [
                    {
                        "title": "Finance Entries (GL)",
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:core_financeentry_changelist"),
                    },
                    {
                        "title": "Reports Dashboard",
                        "icon": "monitoring",
                        "link": reverse_lazy("admin_reports_dashboard"),
                    },
                ],
            },
            {
                "title": "Operations Audit & Logs",
                "icon": "fact_check",
                "items": [
                    {
                        "title": "Process Execution Logs",
                        "icon": "terminal",
                        "link": reverse_lazy("admin:core_processexecutionlog_changelist"),
                    },
                    {
                        "title": "Material Variances",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:core_materialvariancerecord_changelist"),
                    },
                ],
            },
        ],
    },
}
